### ISSUE TITLE
This example fails with visual code on windows

### ISSUE THREAD

**Issue by tadam98** [gnikkoch96/Python-Pomodoro-Timer-GUI#1]
when running main.py the following happens:
```
main.py:9: DeprecationWarning: Call to deprecated function setup_viewport (Use: 
create_viewport()
setup_dearpygui()
show_viewport()).
  dpg.setup_viewport()
```
It is on Windows 10 Version 21H1 (OS Build 19043.1288), conda environment with python 3.7.10. VisualCode 1.6.1.2
dearpygui-1.0.2
playsound-1.3.0

**Comment by gnikkoch96** [comment]
I'll take a look at it. Does the program still run? because I notice that it is just a warning. 

Edit: I just noticed the header, so I assume it didn't work

**Comment by tadam98** [comment]
No. Program does not run and no form is opened.
May I suggest that you consider updating it to work with the latest vesions of the packages ?

The below works:
```
import dearpygui.dearpygui as dpg
def save_callback():
    print("Save Clicked")
dpg.create_context()
dpg.create_viewport()
dpg.setup_dearpygui()
with dpg.window(label="Example Window"):
    dpg.add_text("Hello world")
    dpg.add_button(label="Save", callback=save_callback)
    dpg.add_input_text(label="string")
    dpg.add_slider_float(label="float")
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```

**Comment by gnikkoch96** [comment]
Gotcha, and hmm...I do believe that I followed the same syntax as your example. Sorry if I am not understanding since still kind of new to this.

**Comment by gnikkoch96** [comment]
Ah I think I see what you mean. I didn't realize the dearpygui updated. I'll start making the changes

**Comment by gnikkoch96** [comment]
Alright, I think I got it to work now. You can try it out on the dpg_update branch and let me know if it still doesn't work

**Comment by gnikkoch96** [comment]
I will close the issue for now as I believe that I have updated to the current version of dearpygui
